# EFK logging stack
elasticsearch:
  image: elasticsearch:5
  ports:
    - "9200"
    - "9300"
  volumes:
    - /opt/data/elasticsearch:/usr/share/elasticsearch/data
  log_driver: none
  restart: always

kibana:
  image: kibana:5
  container_name: log
  ports:
    - "5601:5601"
  labels:
    - "traefik.backend=kibana"
  links:
    - elasticsearch
  restart: always

fluentd:
  build: fluentd/
  env_file: .env
  ports:
    - "24224:24224"
  links:
    - elasticsearch
  restart: always

# RabbitMQ
rabbitmq:
  image: rabbitmq
  ports:
    - "5672:5672"

# Heathcliff
heathcliff:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/heathcliff:latest-dev
  environment:
    - HOSTNAME=heathcliff-docker
    - RABBITMQ_HOST=rabbitmq
    - FLUENTD_HOST=fluentd
  links:
    - fluentd
    - rabbitmq

# MySQL
mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_DATABASE=engine

# Engine
engine:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/engine:latest-dev
  container_name: engine
  ports:
    - "8000:8080"
  labels:
    - "traefik.backend=engine"
  environment:
    - FLUENTD_HOST=fluentd
    - HOSTNAME=engine-docker
    - RDS_PASSWORD=docker
    - RDS_HOSTNAME=mysql
    - SERVER_URL=http://engine.localhost
    - MESSAGE_VERSION=V2
  env_file: .env
  links:
    - mysql
    - fluentd
    - rabbitmq

# Docker Management
portainer:
  image: portainer/portainer
  container_name: portainer
  ports:
    - "9000:9000"
  labels:
    - "traefik.backend=portainer"
  volumes:
    - /opt/data/portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always

# Proxy
traefik:
  image: traefik
  command: --web --docker --docker.domain=localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  restart: always

# Backup: `zip -r jenkins.zip /opt/jenkins -x *.m2* -x *.gradle* -x *workspace* -x *.JDK* -x *GrailsInstallation* -x *cache*`
# The mounted volume must have write permissions for the jenkins user, run `chown 1000:1000 -R /opt/jenkins`
jenkins:
  build: jenkins/
  container_name: jenkins
  ports:
    - "8081:8080"
  labels:
    - "traefik.backend=jenkins"
    - "traefik.port=8080"
  volumes:
    - /opt/jenkins:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
  restart: always
