# EFK logging stack
elasticsearch:
  build: elasticsearch/
  ports:
    - "9200"
    - "9300"
  volumes:
    - /opt/data/elasticsearch:/usr/share/elasticsearch/data
kibana:
  build: kibana/
  ports:
    - "5601:5601"
  links:
    - elasticsearch
fluentd:
  build: fluentd/
  ports:
    - "24224:24224"
  links:
    - elasticsearch

# RabbitMQ
rabbitmq:
  image: rabbitmq

# MySQL Alfred
mysql-alfred:
  image: mysql
  environment:
  - MYSQL_ROOT_PASSWORD=docker
  - MYSQL_DATABASE=alfred

# Alfred
alfred:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/alfred:latest
  environment:
    - FLUENTD_HOST=fluentd
    - HOSTNAME=alfred-docker
    - RDS_PASSWORD=docker
    - RDS_HOSTNAME=mysql-alfred
  links:
    - mysql-alfred
    - fluentd
    - rabbitmq

# MySQL Engine
mysql:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_DATABASE=engine

# Engine
engine:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/engine:latest
  ports:
    - "80:8080"
  environment:
    - FLUENTD_HOST=fluentd
    - HOSTNAME=engine-docker
    - RDS_PASSWORD=docker
    - RDS_HOSTNAME=mysql
    - SERVER_URL=http://localhost
  env_file: .env
  links:
    - mysql
    - fluentd
    - rabbitmq
