# EFK logging stack
elasticsearch:
  image: elasticsearch:2
  ports:
    - "9200"
    - "9300"
  volumes:
    - /opt/data/elasticsearch:/usr/share/elasticsearch/data
  restart: always

kibana:
  image: kibana:4
  ports:
    - "5601:5601"
  labels:
    - "traefik.backend=kibana"
    - "traefik.frontend.rule=Host:kibana.localhost"
  links:
    - elasticsearch
  volumes:
    - config:/opt/kibana/config
  restart: always

fluentd:
  build: fluentd/
  ports:
    - "24224:24224"
  links:
    - elasticsearch
  restart: always

# RabbitMQ
rabbitmq:
  image: rabbitmq


# Alfred
alfred:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/alfred:latest-dev
  environment:
    - HOSTNAME=alfred-docker
  links:
    - fluentd
    - rabbitmq

# MySQL
mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_DATABASE=engine

# Engine
engine:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/engine:latest-dev
  ports:
    - "8000:8080"
  labels:
    - "traefik.backend=engine"
    - "traefik.frontend.rule=Host:engine.localhost"
  environment:
    - FLUENTD_HOST=fluentd
    - HOSTNAME=engine-docker
    - RDS_PASSWORD=docker
    - RDS_HOSTNAME=mysql
    - SERVER_URL=http://engine.localhost
  env_file: .env
  links:
    - mysql
    - fluentd
    - rabbitmq

# Docker Management
portainer:
  image: portainer/portainer
  ports:
    - "9000:9000"
  labels:
    - "traefik.backend=portainer"
    - "traefik.frontend.rule=Host:portainer.localhost"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

# Proxy
traefik:
  image: traefik
  command: --web --docker --docker.domain=localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
