# EFK logging stack
elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200"
    - "9300"
  volumes:
    - /opt/data/elasticsearch:/usr/share/elasticsearch/data
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
fluentd:
  build: fluentd/
  ports:
    - "24224:24224"
  links:
    - elasticsearch

# Alfred
alfreddata:
  image: alpine
  entrypoint: /bin/true
  volumes:
    - /usr/local/tomcat/nets
alfred:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/alfred:latest
  ports:
    - "8080:8080"
  environment:
    - FLUENTD_HOST=fluentd
    - HOSTNAME=alfred-docker
  volumes_from:
    - alfreddata
  links:
    - fluentd

# MySQL
mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_DATABASE=engine

# Engine
engine:
  image: 274685854631.dkr.ecr.us-east-1.amazonaws.com/engine:latest
  ports:
    - "80:8080"
  environment:
    - ALFRED_URL=http://localhost:8080
    - FLUENTD_HOST=fluentd
    - HOSTNAME=engine-docker
    - RDS_PASSWORD=docker
    - RDS_HOSTNAME=mysql
    - SERVER_URL=http://localhost
  env_file: .env
  links:
    - mysql
    - fluentd
